#!/bin/bash

# Gather System Identity Information
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATE=$(date)

# System Information
source /etc/os-release
OS="$NAME $VERSION"
UPTIME=$(uptime -p)
CPU=$(lshw -class processor | grep 'product:' | awk -F: '{print $2}' | xargs)
RAM=$(free -h | grep Mem: | awk '{print $2}')
DISKS=$(lshw -class disk | grep -E 'product|size' | awk -F: '{print $2}' | paste -sd ',' -)
VIDEO=$(lshw -class display | grep 'product:' | awk -F: '{print $2}' | xargs)

# Network Information
DEFAULT_IFACE=$(ip route | grep default | awk '{print $5}')
IP_ADDRESS=$(ip -o -4 addr show "$DEFAULT_IFACE" | awk '{print $4}' | cut -d/ -f1)
GATEWAY=$(ip route | grep default | awk '{print $3}')
DNS=$(grep "nameserver" /etc/resolv.conf | head -n 1 | awk '{print $2}')

# System Status
LOGGED_IN_USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd ',' -)
DISK_SPACE=$(df -h --output=target,avail | tail -n +2 | awk '{print $1 " " $2}' | paste -sd ', ' -)
PROCESS_COUNT=$(ps aux --no-heading | wc -l)
LOAD_AVERAGE=$(uptime | awk -F'load average:' '{ print $2 }' | xargs)
PORTS=$(ss -tuln | grep LISTEN | awk '{print $5}' | awk -F: '{print $NF}' | sort -n | uniq | paste -sd ',' -)
UFW_STATUS=$(sudo ufw status | head -n 1)

# Output Report
echo
cat <<EOF
System Report for $HOSTNAME generated by $USERNAME, on $DATE

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: $IP_ADDRESS
Gateway IP: $GATEWAY
DNS Server: $DNS

System Status
-------------
Users Logged In: $LOGGED_IN_USERS
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGE
Listening Network Ports: $PORTS
UFW Status: $UFW_STATUS
EOF
echo

